import React from "react";

const DbBase = () => {
  return (
    <div
      style={{
        height: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "white",
      }}
    >
      <h1
        style={{
          color: "black",
          fontSize: "36px",
          fontWeight: "bold",
        }}
      >
        This page is inProcessing
      </h1>
    </div>
  );
};

export default DbBase;